### ISSUE TITLE
bug with confusion scroll and radius of 0

### ISSUE THREAD

**Issue by Devengel** [SelinaDev/Godot-Roguelike-Tutorial#15]
when item targeting radius is 0, and you activate and cancel or drop the item. the game bugs out and stays in dummy input handler

test it by dropping a confusion scroll or activating it.
so a targeting radius of 1 and above means its an AOE attack, but 0 means its a targeted single tile attack, and -1 no targeting (health potions activation etc) but the logic bugs out at a radius of 0.

I am not sure on how to fix it exactly. input handlers have been confusing so far.

**Comment by SelinaDev** [comment]
I just committed a change to the code that should fix this issue. It does use an extra parameter for `get_item()`, but due to a default argument this only needs to be set in `activate_item()`, in order to tell `get_item()` that a targeting step afterwards is possible. Again, not the cleanest solution overall, but hopefully a relatively clean fix given the current state of the code.
