### ISSUE TITLE
Misc feedback

### ISSUE THREAD

**Issue by thedyze** [SelinaDev/Godot-Roguelike-Tutorial#3]
Since there's no Discussions enabled I hope it's ok to leave some general feedback here.
First up, really appreciate this series, learned so much! So really wondering if blog posts for part 10-12 is coming in the near future?
If you plan to further add to the series, some topics I'd be very interested in:

- Mini map
- Ranged combat (projectiles)
- Smooth movement
- Doors
- Multiple Dungeon floors

I've implemented hold to move several steps with a simple global 'MovementTimer' that starts on key press, stops after 0.2s.  Performs a move if the timer is stopped. Simple yet effective. Smooth movement using tweening I've however not been so successful with. That would be really nice to have a tutorial for!

Thanks again for the work you've put in!

**Comment by SelinaDev** [comment]
Thank you for your feedback!

To answer your first question: Due to some life circumstances I've had either little time or motivation to actually do work on my computer during the last weeks/months. However, I am still woking on the tutorial. I have started working on the writeup for part 10. However, I cannot predict how fast I can upload more tutorials.

It's a big project, and with all these delays I look forward to reaching the goal of completing the series. However, there are other projects in my backlog, so I'll probably let this rest for a while, once I have finished part 13, and achieved pairity with the python tutorial.

I have to say I do like your suggestions, and would love to see them included in such a tutorial eventually. I'll keep them in mind for any future work on the project. There are two (still vague) ideas for this. First, I might revisit this project for a future "r/roguelikedev does the complete roguelike tutorial". Second, there has been more interest in this project than I have imagined, so I am thinking about whether an open-source spin off (i.e., a tutorial series created and expanded by a community) would work. Still, I have to think about that a bit more.

**Comment by thedyze** [comment]
Totally understand, life must come first :). But I really appreciate all the work you've put in so far! 
The amount of information on roguelikes in Godot (especially v4) is quite limited, so this is really valuable.

Looking forward to future blogs/tutorial sections, whenever they may come.
